version: '2'
services:
  # test_komorsan:
  #   image: localhost:5000/komorsan-server:2.1.2
  #   # build: .
  #   container_name: test_komorsan_server
  #   environment:
  #     KOMORSAN_DATABASENAME: komorsan
  #     KOMORSAN_DATABASEADDRESSES: "10.10.10.155:54322"
  #     KOMORSAN_DATABASELOGIN: komorsan
  #     KOMORSAN_DATABASEPASS: "komorsan"
  #   ports:
  #   - "17654:7654"
  #   - "24043:2404"
  #   volumes:
  #   - /var/log/komorsan-main-test:/var/log/komorsan
  #   restart: always
  # komorsan_web:
  #   image: localhost:5000/komorsan_web:2.2_alfa
  #   # build: .
  #   container_name: komorsan_web
  #   ports:
  #   - "8081:8080"
  #   volumes:
  #   - /var/log/web-backend:/var/log/komorsan_web
  #   restart: always
  #   environment:
  #     KOMORSAN_WEB_AUTHORIZEDATABASEIP: test_db # 10.10.10.155
  #     KOMORSAN_WEB_AUTHORIZEDATABASEPORT: 5432
  # test_web_app_testing:
  #   image: localhost:5000/test_web_app_testing:alfa
  #   build: .
  #   container_name: test_web_app_testing
  #   ports:
  #   - "8687:8080"
  #   volumes:
  #   - /var/log/test_web_app_testing:/var/log
  #   restart: always


#   test_db:
#     image: localhost:5000/komorsan-db:2.1
# #    build: PostgresDBCopy
#     container_name: test_db
#     ports:
#     - "54322:5432"
#     volumes:
#     - ./postgres-data:/var/lib/postgresql/data
#     restart: always
#   komorsan_web_frontend:
#     image: localhost:5000/komorsan_web_frontend:2.2_alfa
#     # build: frontend
#     container_name: komorsan_web_frontend
#     ports: 
#     - "8080:80"
#     restart: always
#     #depends_on:
#     #- komorsan_web
#     #links:
#     #- komorsan_web:komorsan_web
#     environment:
#       BACKEND_ADDR: komorsan_web #10.10.10.155
#       BACKEND_PORT: 8080
#     volumes:
#     - ./frontend:/usr/share/nginx/html
#    - /var/local/komorsan/frontend/nginx/conf.d:/etc/nginx/conf.d
  #
  # ------------------------------------------------------------
  #
  # komorsan_web_development:
  #   image: localhost:5000/komorsan_web_development:latest
  #   # build: .
  #   container_name: komorsan_web_development
  #   ports:
  #   - "7071:8080"
  #   volumes:
  #   - /var/log/web-backend:/var/log/komorsan_web_development
  #   restart: always
  #   environment:
  #     KOMORSAN_WEB_AUTHORIZEDATABASEIP: test_db # 10.10.10.155
  #     KOMORSAN_WEB_AUTHORIZEDATABASEPORT: 5432
  #
  # ------------------------------------------------------------
  #
  komorsan_web_frontend_development:
    image: localhost:5000/komorsan_web_frontend_development_vue:latest
    # build: frontend
    container_name: komorsan_web_frontend_development_vue
    ports: 
    - "8080:80"
    # - "8085:80"
    restart: always
    #depends_on:
    #- komorsan_web
    #links:
    #- komorsan_web:komorsan_web
    environment:
      BACKEND_ADDR: 10.10.20.8
      BACKEND_PORT: 7071
        # BACKEND_ADDR: 10.10.20.44
        # BACKEND_PORT: 8081
    volumes:
    - ./frontend/tiles:/usr/share/nginx/html/tiles # Путь к тайлам для оффлайн карт. Первую часть можно менять на нужную папку в файловой системе
    # - /home/max/komorsan_2020/komorsan_web/frontend/:/usr/share/nginx/html
     - /home/max/vue_komorsan/full-version/:/usr/share/nginx/html
    # - /var/local/komorsan/frontend/nginx/conf.d:/etc/nginx/conf.d


docker build -t komorsan_web_frontend_development_vue