version: '2'
services:
  vue_test:
    image: nginx:stable-alpine
    container_name: vue_test
    ports:
    - "8082:80"
    restart: unless-stopped
    environment:
      BACKEND_ADDR: 10.10.20.12 #10.10.10.155
      BACKEND_PORT: 8081
      # BACKEND_ADDR: 10.10.20.44
      # BACKEND_PORT: 8081
    volumes:
      # - /home/max/komorsan_2020/komorsan_web/frontend/:/usr/share/nginx/html
    - ./full-version-back/dist/:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d
